### ISSUE TITLE
"Error: Failed to probe running application type" when trying to flash

### ISSUE THREAD

**Issue by oxypomme** [b2un0/silabs-multipan-docker#16]
Hey,

Wanted to do a multipan without installing haOS (for multiple reasons) so I've found your great work and tried it, but I keep getting an error when trying to flash firmware I can't fix by my own...

Here's my `docker-compose.yml` running on a Ubuntu Server :

<details>

```yml
version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./files/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
    privileged: true
    network_mode: host

  multipan:
    container_name: ha-multipan
    image: b2un0/silabs-multipan-docker:latest
    # restart: unless-stopped
    privileged: true # don't change this !
    network_mode: host # don't change this !
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    volumes:
      - ./files/multipan/:/data
    environment:
      DEVICE: "/dev/ttyUSB0" # only change if your have multiple devices
      BAUDRATE: "460800"
      FLOW_CONTROL: "true" # change to false if you not using SkyConnect

      BACKBONE_IF: "enp2s0" # change this to your network interface
      OTBR_REST_LISTEN_PORT: "8081" # use this within the HomeAssistant integration
      OTBR_WEB_PORT: "8086"

      # ZIGBEED environment variables
      EZSP_LISTEN_PORT: "20108" #

      # UNIVERSAL FLASHER variables
      AUTOFLASH_FIRMWARE: 1 # change to 1 for firmware update
      FIRMWARE: "NabuCasa_SkyConnect_RCP_v4.3.1_rcp-uart-hw-802154_460800.gbl"
```

</details>

And here's the logs I get after running `docker compose up multipan` :

<details>

```
Attaching to ha-multipan
ha-multipan  | [32m2024-04-18 17:42:49 [INFO] Web UI and REST API port are exposed, starting otbr-web.[0m
ha-multipan  | [32m2024-04-18 17:42:49 [INFO] Starting universal-silabs-flasher with /dev/ttyUSB0 (baudrate 460800)[0m
ha-multipan  | [32m2024-04-18 17:42:49 [INFO] Starting mDNS Responder...[0m
ha-multipan  | [32m2024-04-18 17:42:49 [INFO] 
ha-multipan  | ######### ENV ######[0m
ha-multipan  | S6_BEHAVIOUR_IF_STAGE2_FAILS=2
ha-multipan  | HOSTNAME=oxyhome
ha-multipan  | S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
ha-multipan  | S6_SERVICES_READYTIME=50
ha-multipan  | BAUDRATE=460800
ha-multipan  | BACKBONE_IF=enp2s0
ha-multipan  | PWD=/run/s6-rc:s6-rc-init:kLpiiB/servicedirs/s6rc-oneshot-runner
ha-multipan  | BACKBONE_ROUTER=1
ha-multipan  | FLOW_CONTROL=true
ha-multipan  | HOME=/root
ha-multipan  | LANG=C.UTF-8
ha-multipan  | WEB_GUI=1
ha-multipan  | OTBR_LOG_LEVEL=notice
ha-multipan  | S6_VERBOSITY=3
ha-multipan  | S6_STAGE2_HOOK=/etc/s6-overlay/scripts/enable-check.sh
ha-multipan  | AUTOFLASH_FIRMWARE=1
ha-multipan  | OTBR_WEB_PORT=8086
ha-multipan  | OTB_FIREWALL=1
ha-multipan  | CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
ha-multipan  | CPCD_TRACE=false
ha-multipan  | OTBR_BUILD_DEPS=build-essential ninja-build cmake wget ca-certificates   libreadline-dev libncurses-dev libcpputest-dev libdbus-1-dev libavahi-common-dev   libavahi-client-dev libboost-dev libboost-filesystem-dev libboost-system-dev   libnetfilter-queue-dev
ha-multipan  | SHLVL=1
ha-multipan  | DOCKER=1
ha-multipan  | CPCP_DISABLE_ENCRYPTION=true
ha-multipan  | OTBR_REST_LISTEN_PORT=8081
ha-multipan  | DEVICE=/dev/ttyUSB0
ha-multipan  | BORDER_ROUTING=1
ha-multipan  | FIRMWARE=NabuCasa_SkyConnect_RCP_v4.3.1_rcp-uart-hw-802154_460800.gbl
ha-multipan  | PATH=/command:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ha-multipan  | S6_CMD_WAIT_FOR_SERVICES=1
ha-multipan  | NETWORK_DEVICES=0
ha-multipan  | EZSP_LISTEN_PORT=20108
ha-multipan  | DEBIAN_FRONTEND=noninteractive
ha-multipan  | OTBR_ENABLE=1
ha-multipan  | _=/usr/bin/env
ha-multipan  | [32m2024-04-18 17:42:49 [INFO] Generating cpcd configuration.[0m
ha-multipan  | [32m2024-04-18 17:43:15 [INFO] mDNS ended with exit code 4 (signal 0)...[0m
ha-multipan exited with code 1
```

</details>

Any idea on how to fix that ?

**Comment by oxypomme** [comment]
Yup :/

```
$ docker compose run --rm -it --entrypoint "" multipan sh
# ls /data/firmware
NabuCasa_SkyConnect_RCP_v4.3.1_rcp-uart-hw-802154_460800.gbl  NabuCasa_SkyConnect_RCP_v4.4.0_rcp-uart-hw-802154_460800.gbl
```

**Comment by Koky05** [comment]
I think it should be directly in data folder not in firmware folder. I had same problem and copy FW to both directories just for sure.

**Comment by oxypomme** [comment]
> I think it should be directly in data folder not in firmware folder. I had same problem and copy FW to both directories just for sure.

Still no luck, same error while my files are like this

```
$ tree files/multipan/
files/multipan/
├── NabuCasa_SkyConnect_RCP_v4.3.1_rcp-uart-hw-802154_460800.gbl
├── NabuCasa_SkyConnect_RCP_v4.4.0_rcp-uart-hw-802154_460800.gbl
└── firmware
    ├── NabuCasa_SkyConnect_RCP_v4.3.1_rcp-uart-hw-802154_460800.gbl
    └── NabuCasa_SkyConnect_RCP_v4.4.0_rcp-uart-hw-802154_460800.gbl
```

**Comment by Koky05** [comment]
Then try install FW by yourself:
```
python3 -m ensurepip
pip3 install --upgrade pip
pip3 install universal-silabs-flasher
universal-silabs-flasher --device /dev/ttyUSB0 flash --allow-cross-flashing --firmware NabuCasa_SkyConnect_RCP_v4.3.1_rcp-uart-hw-802154_460800.gbl
```

**Comment by oxypomme** [comment]
Same issue :

```
# universal-silabs-flasher --device /dev/ttyUSB0 flash --allow-cross-flashing --firmware /data/firmware/NabuCasa_SkyConnect_RCP_v4.3.1_rcp-uart-hw-802154_460800.gbl
2024-04-19 07:42:26.031 oxyhome universal_silabs_flasher.flash INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version='4.3.1', ezsp_version=None, ot_rcp_version=None, cpc_version=None, fw_type=<FirmwareImageType.RCP_UART_802154: 'rcp-uart-802154'>, baudrate=460800)
2024-04-19 07:42:26.031 oxyhome universal_silabs_flasher.flasher INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
2024-04-19 07:42:28.036 oxyhome universal_silabs_flasher.flasher INFO Probing ApplicationType.CPC at 460800 baud
2024-04-19 07:42:32.351 oxyhome universal_silabs_flasher.flasher INFO Probing ApplicationType.CPC at 115200 baud
2024-04-19 07:42:36.665 oxyhome universal_silabs_flasher.flasher INFO Probing ApplicationType.CPC at 230400 baud
2024-04-19 07:42:40.976 oxyhome universal_silabs_flasher.flasher INFO Probing ApplicationType.EZSP at 115200 baud
2024-04-19 07:42:45.980 oxyhome universal_silabs_flasher.flasher INFO Probing ApplicationType.SPINEL at 460800 baud
Error: Failed to probe running application type
```

But found it may a firmware isssue (https://github.com/NabuCasa/silabs-firmware/issues/28)...

**Comment by oxypomme** [comment]
After a restart, seems like it was because something (probably HA) was using the SkyConnect :

<details>

```
ha-multipan  | 2024-04-19 08:01:18.115 oxyhome universal_silabs_flasher.flasher INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
ha-multipan  | 2024-04-19 08:01:20.121 oxyhome universal_silabs_flasher.flasher INFO Probing ApplicationType.CPC at 460800 baud
ha-multipan  | 2024-04-19 08:01:24.433 oxyhome universal_silabs_flasher.flasher INFO Probing ApplicationType.CPC at 115200 baud
ha-multipan  | 2024-04-19 08:01:28.742 oxyhome universal_silabs_flasher.flasher INFO Probing ApplicationType.CPC at 230400 baud
ha-multipan  | 2024-04-19 08:01:33.052 oxyhome universal_silabs_flasher.flasher INFO Probing ApplicationType.EZSP at 115200 baud
ha-multipan  | 2024-04-19 08:01:34.279 oxyhome universal_silabs_flasher.flasher INFO Detected ApplicationType.EZSP, version '7.1.1.0 build 273' (7.1.1.0.273) at 115200 baudrate (bootloader baudrate None)
ha-multipan  | 2024-04-19 08:01:34.280 oxyhome universal_silabs_flasher.flash INFO Cross-flashing from FirmwareImageType.NCP_UART_HW to FirmwareImageType.RCP_UART_802154
ha-multipan  | 2024-04-19 08:01:35.301 oxyhome bellows.uart ERROR Lost serial connection: SerialException('device reports readiness to read but returned no data (device disconnected or multiple access on port?)')
ha-multipan  | 2024-04-19 08:01:35.301 oxyhome bellows.ezsp INFO NCP entered failed state. No application handler registered, ignoring...
ha-multipan  | Traceback (most recent call last):
ha-multipan  |   File "/usr/local/bin/universal-silabs-flasher", line 8, in <module>
ha-multipan  |     sys.exit(main())
ha-multipan  |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1157, in __call__
ha-multipan  |     return self.main(*args, **kwargs)
ha-multipan  |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1078, in main
ha-multipan  |     rv = self.invoke(ctx)
ha-multipan  |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1688, in invoke
ha-multipan  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
ha-multipan  |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1434, in invoke
ha-multipan  |     return ctx.invoke(self.callback, **ctx.params)
ha-multipan  |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 783, in invoke
ha-multipan  |     return __callback(*args, **kwargs)
ha-multipan  |   File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 33, in new_func
ha-multipan  |     return f(get_current_context(), *args, **kwargs)
ha-multipan  |   File "/usr/local/lib/python3.9/dist-packages/universal_silabs_flasher/flash.py", line 40, in inner
ha-multipan  |     return asyncio.run(f(*args, **kwargs))
ha-multipan  |   File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
ha-multipan  |     return loop.run_until_complete(main)
ha-multipan  |   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
ha-multipan  |     return future.result()
ha-multipan  |   File "/usr/local/lib/python3.9/dist-packages/universal_silabs_flasher/flash.py", line 408, in flash
ha-multipan  |     await flasher.enter_bootloader()
ha-multipan  |   File "/usr/local/lib/python3.9/dist-packages/universal_silabs_flasher/flasher.py", line 255, in enter_bootloader
ha-multipan  |     async with self._connect_ezsp(self.app_baudrate) as ezsp:
ha-multipan  |   File "/usr/lib/python3.9/contextlib.py", line 175, in __aenter__
ha-multipan  |     return await self.gen.__anext__()
ha-multipan  |   File "/usr/local/lib/python3.9/dist-packages/universal_silabs_flasher/emberznet.py", line 41, in connect_ezsp
ha-multipan  |     ezsp = await bellows.ezsp.EZSP.initialize(app_config)
ha-multipan  |   File "/usr/local/lib/python3.9/dist-packages/bellows/ezsp/__init__.py", line 136, in initialize
ha-multipan  |     await ezsp.startup_reset()
ha-multipan  |   File "/usr/local/lib/python3.9/dist-packages/bellows/ezsp/__init__.py", line 125, in startup_reset
ha-multipan  |     await self.reset()
ha-multipan  |   File "/usr/local/lib/python3.9/dist-packages/bellows/ezsp/__init__.py", line 151, in reset
ha-multipan  |     await self._gw.reset()
ha-multipan  |   File "/usr/local/lib/python3.9/dist-packages/bellows/uart.py", line 262, in reset
ha-multipan  |     return await self._reset_future
ha-multipan  |   File "/usr/local/lib/python3.9/dist-packages/serial_asyncio/__init__.py", line 115, in _read_ready
ha-multipan  |     data = self._serial.read(self._max_read_size)
ha-multipan  |   File "/usr/local/lib/python3.9/dist-packages/serial/serialposix.py", line 595, in read
ha-multipan  |     raise SerialException(
ha-multipan  | serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
ha-multipan  | s6-rc: warning: unable to start service universal-silabs-flasher: command exited 1
ha-multipan  | /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
ha-multipan  | /run/s6/basedir/scripts/rc.init: fatal: stopping the container.
```

</details>

Shutdown HA and restarted, and got a new error and then `cpcd` always restart :

<details>

```
ha-multipan  | 2024-04-19 08:04:25 [INFO] Web UI and REST API port are exposed, starting otbr-web.
ha-multipan  | s6-rc-compile: info: parsing /etc/s6-overlay/s6-rc.d/cpcd
ha-multipan  | s6-rc-compile: info: parsing /etc/s6-overlay/s6-rc.d/mdns
ha-multipan  | s6-rc-compile: info: parsing /etc/s6-overlay/s6-rc.d/otbr-agent
ha-multipan  | s6-rc-compile: info: parsing /etc/s6-overlay/s6-rc.d/otbr-web
ha-multipan  | s6-rc-compile: info: parsing /etc/s6-overlay/s6-rc.d/socat-cpcd-tcp
ha-multipan  | s6-rc-compile: info: parsing /etc/s6-overlay/s6-rc.d/universal-silabs-flasher
ha-multipan  | s6-rc-compile: info: parsing /etc/s6-overlay/s6-rc.d/user
ha-multipan  | s6-rc-compile: info: parsing /etc/s6-overlay/s6-rc.d/user2
ha-multipan  | s6-rc-compile: info: parsing /etc/s6-overlay/s6-rc.d/zigbeed
ha-multipan  | s6-rc-compile: info: parsing /package/admin/s6-overlay-3.1.6.2/etc/s6-rc/sources/base
ha-multipan  | s6-rc-compile: info: parsing /package/admin/s6-overlay-3.1.6.2/etc/s6-rc/sources/fix-attrs
ha-multipan  | s6-rc-compile: info: parsing /package/admin/s6-overlay-3.1.6.2/etc/s6-rc/sources/legacy-cont-init
ha-multipan  | s6-rc-compile: info: parsing /package/admin/s6-overlay-3.1.6.2/etc/s6-rc/sources/legacy-services
ha-multipan  | s6-rc-compile: info: parsing /package/admin/s6-overlay-3.1.6.2/etc/s6-rc/sources/top
ha-multipan  | s6-rc-compile: info: making bundles for pipelines
ha-multipan  | s6-rc-compile: info: resolving bundle names
ha-multipan  | s6-rc-compile: info: resolving service names
ha-multipan  | s6-rc-compile: info: writing compiled information to /run/s6/db
ha-multipan  | s6-rc: info: bringing selected services up
ha-multipan  | s6-rc: info: service mdns: starting
ha-multipan  | s6-rc: info: service s6rc-oneshot-runner: starting
ha-multipan  | s6-rc: info: service mdns successfully started
ha-multipan  | s6-rc: info: service s6rc-oneshot-runner successfully started
ha-multipan  | s6-rc: info: service fix-attrs: starting
ha-multipan  | s6-rc: info: service universal-silabs-flasher: starting
ha-multipan  | s6-rc: info: service fix-attrs successfully started
ha-multipan  | s6-rc: info: service legacy-cont-init: starting
ha-multipan  | cont-init: info: running /etc/cont-init.d/check-cpcd-shm.sh
ha-multipan  | 2024-04-19 08:04:25 [INFO] Starting mDNS Responder...
ha-multipan  | Default: mDNSResponder (Engineering Build) (Apr  3 2024 12:19:10) starting
ha-multipan  | Default: Unable to parse DNS server list. Unicast DNS-SD unavailable
ha-multipan  | 2024-04-19 08:04:25 [INFO] Starting universal-silabs-flasher with /dev/ttyUSB0 (baudrate 460800)
ha-multipan  | cont-init: info: /etc/cont-init.d/check-cpcd-shm.sh exited 0
ha-multipan  | cont-init: info: running /etc/cont-init.d/config.sh
ha-multipan  | 2024-04-19 08:04:25 [INFO]
ha-multipan  | ######### ENV ######
ha-multipan  | S6_BEHAVIOUR_IF_STAGE2_FAILS=2
ha-multipan  | HOSTNAME=oxyhome
ha-multipan  | S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
ha-multipan  | S6_SERVICES_READYTIME=50
ha-multipan  | BAUDRATE=460800
ha-multipan  | BACKBONE_IF=enp2s0
ha-multipan  | PWD=/run/s6-rc:s6-rc-init:Opoedf/servicedirs/s6rc-oneshot-runner
ha-multipan  | BACKBONE_ROUTER=1
ha-multipan  | FLOW_CONTROL=true
ha-multipan  | HOME=/root
ha-multipan  | LANG=C.UTF-8
ha-multipan  | WEB_GUI=1
ha-multipan  | OTBR_LOG_LEVEL=notice
ha-multipan  | S6_VERBOSITY=3
ha-multipan  | S6_STAGE2_HOOK=/etc/s6-overlay/scripts/enable-check.sh
ha-multipan  | AUTOFLASH_FIRMWARE=1
ha-multipan  | OTBR_WEB_PORT=8086
ha-multipan  | OTB_FIREWALL=1
ha-multipan  | CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
ha-multipan  | CPCD_TRACE=false
ha-multipan  | OTBR_BUILD_DEPS=build-essential ninja-build cmake wget ca-certificates   libreadline-dev libncurses-dev libcpputest-dev libdbus-1-dev libavahi-common-dev   libavahi-client-dev libboost-dev libboost-filesystem-dev libboost-system-dev   libnetfilter-queue-dev
ha-multipan  | SHLVL=1
ha-multipan  | DOCKER=1
ha-multipan  | CPCP_DISABLE_ENCRYPTION=true
ha-multipan  | OTBR_REST_LISTEN_PORT=8081
ha-multipan  | DEVICE=/dev/ttyUSB0
ha-multipan  | BORDER_ROUTING=1
ha-multipan  | FIRMWARE=NabuCasa_SkyConnect_RCP_v4.4.0_rcp-uart-hw-802154_460800.gbl
ha-multipan  | PATH=/command:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ha-multipan  | S6_CMD_WAIT_FOR_SERVICES=1
ha-multipan  | NETWORK_DEVICES=0
ha-multipan  | EZSP_LISTEN_PORT=20108
ha-multipan  | DEBIAN_FRONTEND=noninteractive
ha-multipan  | OTBR_ENABLE=1
ha-multipan  | _=/usr/bin/env
ha-multipan  | 2024-04-19 08:04:25 [INFO] Generating cpcd configuration.
ha-multipan  | cont-init: info: /etc/cont-init.d/config.sh exited 0
ha-multipan  | s6-rc: info: service legacy-cont-init successfully started
ha-multipan  | 2024-04-19 08:04:26.033 oxyhome universal_silabs_flasher.flash INFO Extracted GBL metadata: NabuCasaMetadata(metadata_version=1, sdk_version='4.4.0', ezsp_version=None, ot_rcp_version=None, cpc_version=None, fw_type=<FirmwareImageType.RCP_UART_802154: 'rcp-uart-802154'>, baudrate=460800)
ha-multipan  | 2024-04-19 08:04:26.034 oxyhome universal_silabs_flasher.flasher INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
ha-multipan  | 2024-04-19 08:04:28.046 oxyhome universal_silabs_flasher.flasher INFO Probing ApplicationType.CPC at 460800 baud
ha-multipan  | 2024-04-19 08:04:32.363 oxyhome universal_silabs_flasher.flasher INFO Probing ApplicationType.CPC at 115200 baud
ha-multipan  | 2024-04-19 08:04:36.679 oxyhome universal_silabs_flasher.flasher INFO Probing ApplicationType.CPC at 230400 baud
ha-multipan  | 2024-04-19 08:04:40.995 oxyhome universal_silabs_flasher.flasher INFO Probing ApplicationType.EZSP at 115200 baud
ha-multipan  | 2024-04-19 08:04:42.225 oxyhome universal_silabs_flasher.flasher INFO Detected ApplicationType.EZSP, version '7.1.1.0 build 273' (7.1.1.0.273) at 115200 baudrate (bootloader baudrate None)
ha-multipan  | 2024-04-19 08:04:42.225 oxyhome universal_silabs_flasher.flash INFO Cross-flashing from FirmwareImageType.NCP_UART_HW to FirmwareImageType.RCP_UART_802154
ha-multipan  | 2024-04-19 08:04:48.431 oxyhome universal_silabs_flasher.flasher INFO Probing ApplicationType.GECKO_BOOTLOADER at 115200 baud
ha-multipan  | 2024-04-19 08:04:49.451 oxyhome universal_silabs_flasher.flasher INFO Detected bootloader version '2.1.1'
ha-multipan  | 2024-04-19 08:04:49.452 oxyhome universal_silabs_flasher.flasher INFO Detected ApplicationType.GECKO_BOOTLOADER, version '2.1.1' at 115200 baudrate (bootloader baudrate 115200)
ha-multipan  | NabuCasa_SkyConnect_RCP_v4.4.0_rcp-uart-hw-802154_460800.gbl
ha-multipan  | s6-rc: info: service universal-silabs-flasher successfully started
ha-multipan  | s6-rc: info: service cpcd: starting
ha-multipan  | 2024-04-19 08:05:08 [INFO] Starting cpcd...
ha-multipan  | WARNING in function 'main' in file /usr/src/cpc-daemon/main.c at line #186 : Running CPCd as 'root' is not recommended. Proceed at your own risk.
ha-multipan  | FATAL in function 'protocol_version_check' in file /usr/src/cpc-daemon/server_core/server_core.c at line #729 : Secondary Protocol v5 doesn't match CPCd Protocol v4
ha-multipan  | [08:05:08:728592] Info : [CPCd v4.3.1.0] [Library API v3] [RCP Protocol v4]
ha-multipan  | [08:05:08:728634] Info : Git commit: 133b29678b3d0bc7578e098d2f46b4d5bcd2ebb4 / branch:
ha-multipan  | [08:05:08:728642] Info : Sources hash: ff8300587e7e4ab1def7a89a272c0baef32f9eb3bff9b0ba06b94e655d652367
ha-multipan  | [08:05:08:728650] WARNING : In function 'main' in file /usr/src/cpc-daemon/main.c at line #186 : Running CPCd as 'root' is not recommended. Proceed at your own risk.
ha-multipan  | [08:05:08:729081] Info : Reading cli arguments
ha-multipan  | [08:05:08:729096] Info : /usr/local/bin/cpcd
ha-multipan  | [08:05:08:730544] Info : Reading configuration
ha-multipan  | [08:05:08:730565] Info :   file_path = /usr/local/etc/cpcd.conf
ha-multipan  | [08:05:08:730570] Info :   instance_name = cpcd_0
ha-multipan  | [08:05:08:730574] Info :   socket_folder = /dev/shm
ha-multipan  | [08:05:08:730578] Info :   operation_mode = MODE_NORMAL
ha-multipan  | [08:05:08:730581] Info :   use_encryption = false
ha-multipan  | [08:05:08:730585] Info :   binding_key_file = /root/.cpcd/binding.key
ha-multipan  | [08:05:08:730589] Info :   stdout_tracing = false
ha-multipan  | [08:05:08:730592] Info :   file_tracing = false
ha-multipan  | [08:05:08:730596] Info :   lttng_tracing = false
ha-multipan  | [08:05:08:730600] Info :   enable_frame_trace = false
ha-multipan  | [08:05:08:730603] Info :   traces_folder = /dev/shm/cpcd-traces
ha-multipan  | [08:05:08:730607] Info :   bus = UART
ha-multipan  | [08:05:08:730611] Info :   uart_baudrate = 460800
ha-multipan  | [08:05:08:730615] Info :   uart_hardflow = true
ha-multipan  | [08:05:08:730619] Info :   uart_file = /dev/ttyUSB0
ha-multipan  | [08:05:08:730623] Info :   fu_recovery_pins_enabled = false
ha-multipan  | [08:05:08:730627] Info :   fu_connect_to_bootloader = false
ha-multipan  | [08:05:08:730631] Info :   fu_enter_bootloader = false
ha-multipan  | [08:05:08:730634] Info :   restart_cpcd = false
ha-multipan  | [08:05:08:730638] Info :   application_version_validation = false
ha-multipan  | [08:05:08:730642] Info :   print_secondary_versions_and_exit = false
ha-multipan  | [08:05:08:730645] Info :   use_noop_keep_alive = false
ha-multipan  | [08:05:08:730649] Info :   reset_sequence = true
ha-multipan  | [08:05:08:730653] Info :   stats_interval = 0
ha-multipan  | [08:05:08:730656] Info :   rlimit_nofile = 2000
ha-multipan  | [08:05:08:730660] Info : ENCRYPTION IS DISABLED
ha-multipan  | [08:05:08:730674] Info : Starting daemon in normal mode
ha-multipan  | [08:05:08:742321] Info : Connecting to Secondary...
ha-multipan  | [08:05:08:821712] Info : RX capability is 256 bytes
ha-multipan  | [08:05:08:821760] Info : Connected to Secondary
ha-multipan  | [08:05:08:825067] Info : Secondary Protocol v5
ha-multipan  | [08:05:08:825094] *** ASSERT *** : FATAL in function 'protocol_version_check' in file /usr/src/cpc-daemon/server_core/server_core.c at line #729 : Secondary Protocol v5 doesn't match CPCd Protocol v4
ha-multipan  | [08:05:09:825535] Info : Daemon exiting with status EXIT_FAILURE
ha-multipan  | Logger buffer size = 28672, highwater mark = 2441 : 8.51%. Lost logs : 0
ha-multipan  | 2024-04-19 08:05:09 [INFO] CPC ended with exit code 1 (signal 0)...
ha-multipan  | 2024-04-19 08:05:10 [INFO] Starting cpcd...
```

</details>

**Comment by b2un0** [comment]
> ha-multipan  | [08:05:08:825094] *** ASSERT *** : FATAL in function 'protocol_version_check' in file /usr/src/cpc-daemon/server_core/server_core.c at line #729 : Secondary Protocol v5 doesn't match CPCd Protocol v4

see here https://github.com/b2un0/silabs-multipan-docker/wiki/Secondary-Protocol-v5-doesn't-match-CPCd-Protocol-v4

**Comment by b2un0** [comment]
also remove the `privileged: true` **AND**  the `/dev/ttyUSB0` volume from your HA Container ❗

**Comment by oxypomme** [comment]
> > ha-multipan  | [08:05:08:825094] *** ASSERT *** : FATAL in function 'protocol_version_check' in file /usr/src/cpc-daemon/server_core/server_core.c at line #729 : Secondary Protocol v5 doesn't match CPCd Protocol v4
> 
> see here https://github.com/b2un0/silabs-multipan-docker/wiki/Secondary-Protocol-v5-doesn't-match-CPCd-Protocol-v4

Was trying that, seems like downgrading to `v4.3.1` did the trick

**Comment by oxypomme** [comment]
> also remove the `privileged: true` **AND** the `/dev/ttyUSB0` volume from your HA Container ❗ both makes no sense

Followed https://www.home-assistant.io/installation/linux#exposing-devices for the volume, integrations weren't working without this.

And followed https://www.home-assistant.io/installation/linux#docker-compose for the `privileged: true`.

I'll try without them tho

**Comment by b2un0** [comment]
> Followed https://www.home-assistant.io/installation/linux#exposing-devices for the volume, integrations weren't working without this.

this is only required if you want to use a "zigbee only" stick directly in HA
but that's not possible because you want to use multipan - which only this container allows you to do

**Comment by b2un0** [comment]
for the ZHA integration in HA you should be read the "ZHA" section in my README.md.

**Comment by oxypomme** [comment]
Okay works like wonders, kinda broke the Bluetooth integration, but it should be fine.

Thanks all, closing the issue 🎉

**Comment by b2un0** [comment]
for bluetooth use this:

```yaml

homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    group_add:
      - dialout # new
    volumes:
      - ./files/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/run/dbus:/run/dbus:ro # check if it relady "/run/dbus" or "/var/run/dbus" !!
    restart: unless-stopped
    network_mode: host
```
i your use bluetooth too and in my case the `group_add` did the trick
